services:
  backend:
    build: .
    container_name: app
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
    - 8000:8000
    depends_on:
    - db
    env_file:
    - .env
    environment:
    - "DATABASE_URL=postgres://postgres:postgres@db:5432/postgres"

  db:
    image: postgres:16.2
    container_name: app_db
    ports:
    - '5432:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "-e POSTGRES_PASSWORD=password"

volumes:
  postgres_data: